server:
  port: 9011 #端口
spring:
  application:
    name: service-product #服务名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/xml/*.xml
  global-config:
    db-config:
      id-type: id_worker_str
      logic-not-delete-value: 0
      login-delete-value: 1
#配置Eureka
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/    #多个eurekaserver之间用,隔开
#  instance:
#    prefer-ip-address: true #使用ip地址注册