spring:
  application:
   name: eureka_server1
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
#    registerWithEureka: false #是否将自己注册到注册中心
#    fetchRegistry: false #是否从eureka中获取注册信息
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
